### ISSUE TITLE
Outdated community translations

### ISSUE THREAD

**Issue by Lykrast** [Lykrast/JETIF#11]
The following translations were made in prior verions and thus are lacking some of the newer strings;

- [x] `de_de` originally made by @MaxNeedsSnacks (#12)
- [x] `zh_cn` originally made by @mcBegins2Snow (#13)
- [x] `zh_tw` also by @mcBegins2Snow (#13)

Hopefully I did it right to mention them.
